version: '3.7'

x-common-variables: &common-variables
  REDIS_PORT: 6379
  REDIS_HOST: "redis-server"

services:
  redis-server:
    image: "redis"
    ports:
      - "6379:6379"

  scraper-fa1:
    build: .
    working_dir: /app
    environment:
      <<: *common-variables
      CRAWL_TYPE: "FA1"

  scraper-fa2:
    build: .
    working_dir: /app
    environment:
      <<: *common-variables
      CRAWL_TYPE: "FA2"

  scraper-fa34:
    build: .
    working_dir: /app
    environment:
      <<: *common-variables
      CRAWL_TYPE: "FA34"

  scraper-fa35:
    build: .
    working_dir: /app
    environment:
      <<: *common-variables
      CRAWL_TYPE: "FA35"
