apiVersion: batch/v1
kind: CronJob
metadata:
  name: scraper-cronjob
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      completions: 1
      parallelism: 1
      template:
        spec:
          containers:
            - name: scraper-fa1
              image: marsboy02/node-scraper:latest
              env:
                - name: CRAWL_TYPE
                  value: "FA1"
                - name: REDIS_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: scraper-cm
                      key : REDIS_HOST
                - name: REDIS_PORT
                  valueFrom:
                    configMapKeyRef:
                      name: scraper-cm
                      key: REDIS_PORT
            - name: scraper-fa2
              image: marsboy02/node-scraper:latest
              env:
                - name: CRAWL_TYPE
                  value: "FA2"
                - name: REDIS_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: scraper-cm
                      key: REDIS_HOST
                - name: REDIS_PORT
                  valueFrom:
                    configMapKeyRef:
                      name: scraper-cm
                      key: REDIS_PORT
            - name: scraper-fa34
              image: marsboy02/node-scraper:latest
              env:
                - name: CRAWL_TYPE
                  value: "FA34"
                - name: REDIS_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: scraper-cm
                      key: REDIS_HOST
                - name: REDIS_PORT
                  valueFrom:
                    configMapKeyRef:
                      name: scraper-cm
                      key: REDIS_PORT
            - name: scraper-fa35
              image: marsboy02/node-scraper:latest
              env:
                - name: CRAWL_TYPE
                  value: "FA35"
                - name: REDIS_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: scraper-cm
                      key: REDIS_HOST
                - name: REDIS_PORT
                  valueFrom:
                    configMapKeyRef:
                      name: scraper-cm
                      key: REDIS_PORT
          restartPolicy: OnFailure
