apiVersion: v1
kind: Service
metadata:
  name: scraper-redis
spec:
  type: ClusterIP
  clusterIP: 172.20.100.100
  selector:
    app: scraper-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
